'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PC_.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AppDiscovery.log.
        '''</summary>
        Friend ReadOnly Property AppDiscovery() As String
            Get
                Return ResourceManager.GetString("AppDiscovery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AppEnforce.log.
        '''</summary>
        Friend ReadOnly Property AppEnforce() As String
            Get
                Return ResourceManager.GetString("AppEnforce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AppIntentEval.log.
        '''</summary>
        Friend ReadOnly Property AppIntentEval() As String
            Get
                Return ResourceManager.GetString("AppIntentEval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AssetAdvisor.log.
        '''</summary>
        Friend ReadOnly Property AssetAdvisor() As String
            Get
                Return ResourceManager.GetString("AssetAdvisor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BgbHttpProxy.log.
        '''</summary>
        Friend ReadOnly Property BgbHttpProxy() As String
            Get
                Return ResourceManager.GetString("BgbHttpProxy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CAS.log.
        '''</summary>
        Friend ReadOnly Property CAS() As String
            Get
                Return ResourceManager.GetString("CAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_1.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_1() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_10.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_10() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_11.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_11() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_12.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_12() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_13.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_13() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_14.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_14() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_15.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_15() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_16.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_16() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_17.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_17() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_18.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_18() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_19.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_19() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_2.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_2() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_20.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_20() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_21.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_21() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_22.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_22() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_23.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_23() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_24.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_24() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_25.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_25() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_26.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_26() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_27.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_27() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_28.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_28() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_3.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_3() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_4.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_4() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_5.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_5() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_6.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_6() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_7.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_7() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_8.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_8() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCM_COMMAND_9.
        '''</summary>
        Friend ReadOnly Property CCM_COMMAND_9() As String
            Get
                Return ResourceManager.GetString("CCM_COMMAND_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ccm32BitLauncher.log.
        '''</summary>
        Friend ReadOnly Property Ccm32BitLauncher() As String
            Get
                Return ResourceManager.GetString("Ccm32BitLauncher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CcmEval.log.
        '''</summary>
        Friend ReadOnly Property CcmEval() As String
            Get
                Return ResourceManager.GetString("CcmEval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CcmEvalTask.log.
        '''</summary>
        Friend ReadOnly Property CcmEvalTask() As String
            Get
                Return ResourceManager.GetString("CcmEvalTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CcmExec.log.
        '''</summary>
        Friend ReadOnly Property CcmExec() As String
            Get
                Return ResourceManager.GetString("CcmExec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CcmMessaging.log.
        '''</summary>
        Friend ReadOnly Property CcmMessaging() As String
            Get
                Return ResourceManager.GetString("CcmMessaging", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCMNotificationAgent.log.
        '''</summary>
        Friend ReadOnly Property CCMNotificationAgent() As String
            Get
                Return ResourceManager.GetString("CCMNotificationAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ccmperf.log.
        '''</summary>
        Friend ReadOnly Property Ccmperf() As String
            Get
                Return ResourceManager.GetString("Ccmperf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CcmRepair.log.
        '''</summary>
        Friend ReadOnly Property CcmRepair() As String
            Get
                Return ResourceManager.GetString("CcmRepair", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CcmRestart.log.
        '''</summary>
        Friend ReadOnly Property CcmRestart() As String
            Get
                Return ResourceManager.GetString("CcmRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CCMSDKProvider.log.
        '''</summary>
        Friend ReadOnly Property CCMSDKProvider() As String
            Get
                Return ResourceManager.GetString("CCMSDKProvider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ccmsetup.log.
        '''</summary>
        Friend ReadOnly Property ccmsetup() As String
            Get
                Return ResourceManager.GetString("ccmsetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ccmsetup_ccmeval.log.
        '''</summary>
        Friend ReadOnly Property ccmsetup_ccmeval() As String
            Get
                Return ResourceManager.GetString("ccmsetup_ccmeval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CertificateMaintenance.log.
        '''</summary>
        Friend ReadOnly Property CertificateMaintenance() As String
            Get
                Return ResourceManager.GetString("CertificateMaintenance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CHOICE_MW_BYPASS_NO.
        '''</summary>
        Friend ReadOnly Property ChoiceMWBypassNo() As String
            Get
                Return ResourceManager.GetString("ChoiceMWBypassNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CHOICE_MW_BYPASS_YES.
        '''</summary>
        Friend ReadOnly Property ChoiceMWBypassYes() As String
            Get
                Return ResourceManager.GetString("ChoiceMWBypassYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CIAgent.log.
        '''</summary>
        Friend ReadOnly Property CIAgent() As String
            Get
                Return ResourceManager.GetString("CIAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CIDownloader.log.
        '''</summary>
        Friend ReadOnly Property CIDownloader() As String
            Get
                Return ResourceManager.GetString("CIDownloader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CITaskManager.log.
        '''</summary>
        Friend ReadOnly Property CITaskManager() As String
            Get
                Return ResourceManager.GetString("CITaskManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CITaskMgr.log.
        '''</summary>
        Friend ReadOnly Property CITaskMgr() As String
            Get
                Return ResourceManager.GetString("CITaskMgr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to client.msi.log.
        '''</summary>
        Friend ReadOnly Property client_msi() As String
            Get
                Return ResourceManager.GetString("client_msi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ClientAuth.log.
        '''</summary>
        Friend ReadOnly Property ClientAuth() As String
            Get
                Return ResourceManager.GetString("ClientAuth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ClientIDManagerStartup.log.
        '''</summary>
        Friend ReadOnly Property ClientIDManagerStartup() As String
            Get
                Return ResourceManager.GetString("ClientIDManagerStartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ClientLocation.log.
        '''</summary>
        Friend ReadOnly Property ClientLocation() As String
            Get
                Return ResourceManager.GetString("ClientLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GC_PROFILE_LOG.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item0() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GC_PROFILE_PC.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item1() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SCCM_REPORTS_APPS.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item10() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADMIN_LAUNCHER.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item12() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GC_PROFILE_USER.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item2() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EXPLORER++.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item4() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVENT_VIEWER.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item5() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COMPUTER_MANAGEMENT.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item6() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SERVICES.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item7() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SCCM_REPORTS_PKG.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Item9() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Item9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --------------------------------------------------------.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_separator() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_separator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT_ITEM.
        '''</summary>
        Friend ReadOnly Property cmb_Combo_Tools_Text() As String
            Get
                Return ResourceManager.GetString("cmb_Combo_Tools_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CMHttpsReadiness.log.
        '''</summary>
        Friend ReadOnly Property CMHttpsReadiness() As String
            Get
                Return ResourceManager.GetString("CMHttpsReadiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CmRcService.log.
        '''</summary>
        Friend ReadOnly Property CmRcService() As String
            Get
                Return ResourceManager.GetString("CmRcService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ConfigMgrSoftwareCatalog.log.
        '''</summary>
        Friend ReadOnly Property ConfigMgrSoftwareCatalog() As String
            Get
                Return ResourceManager.GetString("ConfigMgrSoftwareCatalog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_ACTION.
        '''</summary>
        Friend ReadOnly Property ConfirmAction() As String
            Get
                Return ResourceManager.GetString("ConfirmAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_COMPUTER_NAME.
        '''</summary>
        Friend ReadOnly Property ConfirmComputerName() As String
            Get
                Return ResourceManager.GetString("ConfirmComputerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_GPO_UPDATE.
        '''</summary>
        Friend ReadOnly Property ConfirmGPOUpdate() As String
            Get
                Return ResourceManager.GetString("ConfirmGPOUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_MW_BYPASS.
        '''</summary>
        Friend ReadOnly Property ConfirmMWBypass() As String
            Get
                Return ResourceManager.GetString("ConfirmMWBypass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_REBOOT.
        '''</summary>
        Friend ReadOnly Property ConfirmReboot() As String
            Get
                Return ResourceManager.GetString("ConfirmReboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_REMOVE_HISTORY.
        '''</summary>
        Friend ReadOnly Property ConfirmRemoveHistory() As String
            Get
                Return ResourceManager.GetString("ConfirmRemoveHistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_REMOVE_MW.
        '''</summary>
        Friend ReadOnly Property ConfirmRemoveMW() As String
            Get
                Return ResourceManager.GetString("ConfirmRemoveMW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_REMOVE_WMI_NAMESPACE.
        '''</summary>
        Friend ReadOnly Property ConfirmRemoveWMINamespace() As String
            Get
                Return ResourceManager.GetString("ConfirmRemoveWMINamespace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_START_SERVICE.
        '''</summary>
        Friend ReadOnly Property ConfirmStartService() As String
            Get
                Return ResourceManager.GetString("ConfirmStartService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_STOP_PROCESS.
        '''</summary>
        Friend ReadOnly Property ConfirmStopProcess() As String
            Get
                Return ResourceManager.GetString("ConfirmStopProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRM_STOP_SERVICE.
        '''</summary>
        Friend ReadOnly Property ConfirmStopService() As String
            Get
                Return ResourceManager.GetString("ConfirmStopService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ContentTransferManager.log.
        '''</summary>
        Friend ReadOnly Property ContentTransferManager() As String
            Get
                Return ResourceManager.GetString("ContentTransferManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DataTransferService.log.
        '''</summary>
        Friend ReadOnly Property DataTransferService() As String
            Get
                Return ResourceManager.GetString("DataTransferService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DCMAgent.log.
        '''</summary>
        Friend ReadOnly Property DCMAgent() As String
            Get
                Return ResourceManager.GetString("DCMAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DCMReporting.log.
        '''</summary>
        Friend ReadOnly Property DCMReporting() As String
            Get
                Return ResourceManager.GetString("DCMReporting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DcmWmiProvider.log.
        '''</summary>
        Friend ReadOnly Property DcmWmiProvider() As String
            Get
                Return ResourceManager.GetString("DcmWmiProvider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DNS_ERROR.
        '''</summary>
        Friend ReadOnly Property DNSError() As String
            Get
                Return ResourceManager.GetString("DNSError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EndpointProtectionAgent.log.
        '''</summary>
        Friend ReadOnly Property EndpointProtectionAgent() As String
            Get
                Return ResourceManager.GetString("EndpointProtectionAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error_BAD_AD.
        '''</summary>
        Friend ReadOnly Property Error_BAD_AD() As String
            Get
                Return ResourceManager.GetString("Error_BAD_AD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_ANALYZE_BEFORE_RETRY.
        '''</summary>
        Friend ReadOnly Property ErrorAnalyzeBeforeRetry() As String
            Get
                Return ResourceManager.GetString("ErrorAnalyzeBeforeRetry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_CONNECTION.
        '''</summary>
        Friend ReadOnly Property ErrorConnection() As String
            Get
                Return ResourceManager.GetString("ErrorConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_REGISTRY_CONNECTION.
        '''</summary>
        Friend ReadOnly Property ErrorRegistryConnection() As String
            Get
                Return ResourceManager.GetString("ErrorRegistryConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_REMOVE_HISTORY.
        '''</summary>
        Friend ReadOnly Property ErrorRemoveHistory() As String
            Get
                Return ResourceManager.GetString("ErrorRemoveHistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_SITE_CODE.
        '''</summary>
        Friend ReadOnly Property ErrorSiteCode() As String
            Get
                Return ResourceManager.GetString("ErrorSiteCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_START_SERVICE.
        '''</summary>
        Friend ReadOnly Property ErrorStartService() As String
            Get
                Return ResourceManager.GetString("ErrorStartService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_STOP_SERVICE.
        '''</summary>
        Friend ReadOnly Property ErrorStopService() As String
            Get
                Return ResourceManager.GetString("ErrorStopService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_TASK_SCHEDULE.
        '''</summary>
        Friend ReadOnly Property ErrorTaskSchedule() As String
            Get
                Return ResourceManager.GetString("ErrorTaskSchedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_UNEXPECTED.
        '''</summary>
        Friend ReadOnly Property ErrorUnexpected() As String
            Get
                Return ResourceManager.GetString("ErrorUnexpected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR_UNREACHABLE_COMPUTER.
        '''</summary>
        Friend ReadOnly Property ErrorUnreachableComputer() As String
            Get
                Return ResourceManager.GetString("ErrorUnreachableComputer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_0.
        '''</summary>
        Friend ReadOnly Property EvaluationState0() As String
            Get
                Return ResourceManager.GetString("EvaluationState0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_1.
        '''</summary>
        Friend ReadOnly Property EvaluationState1() As String
            Get
                Return ResourceManager.GetString("EvaluationState1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_10.
        '''</summary>
        Friend ReadOnly Property EvaluationState10() As String
            Get
                Return ResourceManager.GetString("EvaluationState10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_11.
        '''</summary>
        Friend ReadOnly Property EvaluationState11() As String
            Get
                Return ResourceManager.GetString("EvaluationState11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_12.
        '''</summary>
        Friend ReadOnly Property EvaluationState12() As String
            Get
                Return ResourceManager.GetString("EvaluationState12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_13.
        '''</summary>
        Friend ReadOnly Property EvaluationState13() As String
            Get
                Return ResourceManager.GetString("EvaluationState13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_14.
        '''</summary>
        Friend ReadOnly Property EvaluationState14() As String
            Get
                Return ResourceManager.GetString("EvaluationState14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_15.
        '''</summary>
        Friend ReadOnly Property EvaluationState15() As String
            Get
                Return ResourceManager.GetString("EvaluationState15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_16.
        '''</summary>
        Friend ReadOnly Property EvaluationState16() As String
            Get
                Return ResourceManager.GetString("EvaluationState16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_17.
        '''</summary>
        Friend ReadOnly Property EvaluationState17() As String
            Get
                Return ResourceManager.GetString("EvaluationState17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_18.
        '''</summary>
        Friend ReadOnly Property EvaluationState18() As String
            Get
                Return ResourceManager.GetString("EvaluationState18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_19.
        '''</summary>
        Friend ReadOnly Property EvaluationState19() As String
            Get
                Return ResourceManager.GetString("EvaluationState19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_2.
        '''</summary>
        Friend ReadOnly Property EvaluationState2() As String
            Get
                Return ResourceManager.GetString("EvaluationState2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_20.
        '''</summary>
        Friend ReadOnly Property EvaluationState20() As String
            Get
                Return ResourceManager.GetString("EvaluationState20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_21.
        '''</summary>
        Friend ReadOnly Property EvaluationState21() As String
            Get
                Return ResourceManager.GetString("EvaluationState21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_22.
        '''</summary>
        Friend ReadOnly Property EvaluationState22() As String
            Get
                Return ResourceManager.GetString("EvaluationState22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_23.
        '''</summary>
        Friend ReadOnly Property EvaluationState23() As String
            Get
                Return ResourceManager.GetString("EvaluationState23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_24.
        '''</summary>
        Friend ReadOnly Property EvaluationState24() As String
            Get
                Return ResourceManager.GetString("EvaluationState24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_25.
        '''</summary>
        Friend ReadOnly Property EvaluationState25() As String
            Get
                Return ResourceManager.GetString("EvaluationState25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_26.
        '''</summary>
        Friend ReadOnly Property EvaluationState26() As String
            Get
                Return ResourceManager.GetString("EvaluationState26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_27.
        '''</summary>
        Friend ReadOnly Property EvaluationState27() As String
            Get
                Return ResourceManager.GetString("EvaluationState27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_28.
        '''</summary>
        Friend ReadOnly Property EvaluationState28() As String
            Get
                Return ResourceManager.GetString("EvaluationState28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_3.
        '''</summary>
        Friend ReadOnly Property EvaluationState3() As String
            Get
                Return ResourceManager.GetString("EvaluationState3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_4.
        '''</summary>
        Friend ReadOnly Property EvaluationState4() As String
            Get
                Return ResourceManager.GetString("EvaluationState4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_5.
        '''</summary>
        Friend ReadOnly Property EvaluationState5() As String
            Get
                Return ResourceManager.GetString("EvaluationState5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_6.
        '''</summary>
        Friend ReadOnly Property EvaluationState6() As String
            Get
                Return ResourceManager.GetString("EvaluationState6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_7.
        '''</summary>
        Friend ReadOnly Property EvaluationState7() As String
            Get
                Return ResourceManager.GetString("EvaluationState7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_8.
        '''</summary>
        Friend ReadOnly Property EvaluationState8() As String
            Get
                Return ResourceManager.GetString("EvaluationState8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_9.
        '''</summary>
        Friend ReadOnly Property EvaluationState9() As String
            Get
                Return ResourceManager.GetString("EvaluationState9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EVALUATION_STATE_Else.
        '''</summary>
        Friend ReadOnly Property EvaluationStateElse() As String
            Get
                Return ResourceManager.GetString("EvaluationStateElse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to execmgr.log.
        '''</summary>
        Friend ReadOnly Property execmgr() As String
            Get
                Return ResourceManager.GetString("execmgr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ExpressionSolver.log.
        '''</summary>
        Friend ReadOnly Property ExpressionSolver() As String
            Get
                Return ResourceManager.GetString("ExpressionSolver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ExternalEventAgent.log.
        '''</summary>
        Friend ReadOnly Property ExternalEventAgent() As String
            Get
                Return ResourceManager.GetString("ExternalEventAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FileBITS.log.
        '''</summary>
        Friend ReadOnly Property FileBITS() As String
            Get
                Return ResourceManager.GetString("FileBITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FileSystemFile.log.
        '''</summary>
        Friend ReadOnly Property FileSystemFile() As String
            Get
                Return ResourceManager.GetString("FileSystemFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FSPStateMessage.log.
        '''</summary>
        Friend ReadOnly Property FSPStateMessage() As String
            Get
                Return ResourceManager.GetString("FSPStateMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InternetProxy.log.
        '''</summary>
        Friend ReadOnly Property InternetProxy() As String
            Get
                Return ResourceManager.GetString("InternetProxy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InventoryAgent.log.
        '''</summary>
        Friend ReadOnly Property InventoryAgent() As String
            Get
                Return ResourceManager.GetString("InventoryAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to loadstate.log.
        '''</summary>
        Friend ReadOnly Property loadstate() As String
            Get
                Return ResourceManager.GetString("loadstate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LocationCache.log.
        '''</summary>
        Friend ReadOnly Property LocationCache() As String
            Get
                Return ResourceManager.GetString("LocationCache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LocationServices.log.
        '''</summary>
        Friend ReadOnly Property LocationServices() As String
            Get
                Return ResourceManager.GetString("LocationServices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MaintenanceCoordinator.log.
        '''</summary>
        Friend ReadOnly Property MaintenanceCoordinator() As String
            Get
                Return ResourceManager.GetString("MaintenanceCoordinator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MESSAGE_DELETE_TS.
        '''</summary>
        Friend ReadOnly Property Message_Delete_TS() As String
            Get
                Return ResourceManager.GetString("Message_Delete_TS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MESSAGE_DOMAIN_MISSING.
        '''</summary>
        Friend ReadOnly Property Message_Domain_Missing() As String
            Get
                Return ResourceManager.GetString("Message_Domain_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MESSAGE_FILES_INI_MISSING.
        '''</summary>
        Friend ReadOnly Property Message_file_ini_missing() As String
            Get
                Return ResourceManager.GetString("Message_file_ini_missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MESSAGE_LONG_WAIT_TIME.
        '''</summary>
        Friend ReadOnly Property Message_long_wait_time() As String
            Get
                Return ResourceManager.GetString("Message_long_wait_time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MESSAGE_REBOOT.
        '''</summary>
        Friend ReadOnly Property MessageReboot() As String
            Get
                Return ResourceManager.GetString("MessageReboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MESSAGE_REINSTALL_CLIENT.
        '''</summary>
        Friend ReadOnly Property MessageReinstallClient() As String
            Get
                Return ResourceManager.GetString("MessageReinstallClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mifprovider.log.
        '''</summary>
        Friend ReadOnly Property Mifprovider() As String
            Get
                Return ResourceManager.GetString("Mifprovider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing_INI_Files.
        '''</summary>
        Friend ReadOnly Property Missing_INI_Files() As String
            Get
                Return ResourceManager.GetString("Missing_INI_Files", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MSG_CLIPBOARD.
        '''</summary>
        Friend ReadOnly Property MsgClipboard() As String
            Get
                Return ResourceManager.GetString("MsgClipboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mtrmgr.log.
        '''</summary>
        Friend ReadOnly Property mtrmgr() As String
            Get
                Return ResourceManager.GetString("mtrmgr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic_Ok_mage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic_Ok_mage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PolicyAgent.log.
        '''</summary>
        Friend ReadOnly Property PolicyAgent() As String
            Get
                Return ResourceManager.GetString("PolicyAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PolicyAgentProvider.log.
        '''</summary>
        Friend ReadOnly Property PolicyAgentProvider() As String
            Get
                Return ResourceManager.GetString("PolicyAgentProvider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PolicyEvaluator.log.
        '''</summary>
        Friend ReadOnly Property PolicyEvaluator() As String
            Get
                Return ResourceManager.GetString("PolicyEvaluator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PolicyPlatformClient.log.
        '''</summary>
        Friend ReadOnly Property PolicyPlatformClient() As String
            Get
                Return ResourceManager.GetString("PolicyPlatformClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PolicySdk.log.
        '''</summary>
        Friend ReadOnly Property PolicySdk() As String
            Get
                Return ResourceManager.GetString("PolicySdk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pwrmgmt.log.
        '''</summary>
        Friend ReadOnly Property Pwrmgmt() As String
            Get
                Return ResourceManager.GetString("Pwrmgmt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PwrProvider.log.
        '''</summary>
        Friend ReadOnly Property PwrProvider() As String
            Get
                Return ResourceManager.GetString("PwrProvider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RebootCoordinator.log.
        '''</summary>
        Friend ReadOnly Property RebootCoordinator() As String
            Get
                Return ResourceManager.GetString("RebootCoordinator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ScanAgent.log.
        '''</summary>
        Friend ReadOnly Property ScanAgent() As String
            Get
                Return ResourceManager.GetString("ScanAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to scanstate.log.
        '''</summary>
        Friend ReadOnly Property scanstate() As String
            Get
                Return ResourceManager.GetString("scanstate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scheduler.log.
        '''</summary>
        Friend ReadOnly Property Scheduler() As String
            Get
                Return ResourceManager.GetString("Scheduler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SdmAgent.log.
        '''</summary>
        Friend ReadOnly Property SdmAgent() As String
            Get
                Return ResourceManager.GetString("SdmAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M/dd/yyyy - hh:mm tt.
        '''</summary>
        Friend ReadOnly Property ServiceWindowDateTimeFormat() As String
            Get
                Return ResourceManager.GetString("ServiceWindowDateTimeFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServiceWindowManager.log.
        '''</summary>
        Friend ReadOnly Property ServiceWindowManager() As String
            Get
                Return ResourceManager.GetString("ServiceWindowManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hh:mm.
        '''</summary>
        Friend ReadOnly Property ServiceWindowTimeFormat() As String
            Get
                Return ResourceManager.GetString("ServiceWindowTimeFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setupact.log.
        '''</summary>
        Friend ReadOnly Property Setupact() As String
            Get
                Return ResourceManager.GetString("Setupact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setupapi.log.
        '''</summary>
        Friend ReadOnly Property Setupapi() As String
            Get
                Return ResourceManager.GetString("Setupapi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setuperr.log.
        '''</summary>
        Friend ReadOnly Property Setuperr() As String
            Get
                Return ResourceManager.GetString("Setuperr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to setuppolicyevaluator.log.
        '''</summary>
        Friend ReadOnly Property setuppolicyevaluator() As String
            Get
                Return ResourceManager.GetString("setuppolicyevaluator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to smpisapi.log.
        '''</summary>
        Friend ReadOnly Property smpisapi() As String
            Get
                Return ResourceManager.GetString("smpisapi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to smscliui.log.
        '''</summary>
        Friend ReadOnly Property smscliui() As String
            Get
                Return ResourceManager.GetString("smscliui", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Smsts.log.
        '''</summary>
        Friend ReadOnly Property Smsts() As String
            Get
                Return ResourceManager.GetString("Smsts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SmsWusHandler.log.
        '''</summary>
        Friend ReadOnly Property SmsWusHandler() As String
            Get
                Return ResourceManager.GetString("SmsWusHandler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SoftwareCatalogUpdateEndpoint.log.
        '''</summary>
        Friend ReadOnly Property SoftwareCatalogUpdateEndpoint() As String
            Get
                Return ResourceManager.GetString("SoftwareCatalogUpdateEndpoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SoftwareCenterSystemTasks.log.
        '''</summary>
        Friend ReadOnly Property SoftwareCenterSystemTasks() As String
            Get
                Return ResourceManager.GetString("SoftwareCenterSystemTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SrcUpdateMgr.log.
        '''</summary>
        Friend ReadOnly Property SrcUpdateMgr() As String
            Get
                Return ResourceManager.GetString("SrcUpdateMgr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StateMessage.log.
        '''</summary>
        Friend ReadOnly Property StateMessage() As String
            Get
                Return ResourceManager.GetString("StateMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StatusAgent.log.
        '''</summary>
        Friend ReadOnly Property StatusAgent() As String
            Get
                Return ResourceManager.GetString("StatusAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SUCCESS_PLANNED_INSTALL.
        '''</summary>
        Friend ReadOnly Property SuccessPlannedInstall() As String
            Get
                Return ResourceManager.GetString("SuccessPlannedInstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SUCCESS_REBOOT.
        '''</summary>
        Friend ReadOnly Property SuccessReboot() As String
            Get
                Return ResourceManager.GetString("SuccessReboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SUCCESS_REMOVE_HISTORY.
        '''</summary>
        Friend ReadOnly Property SuccessRemoveHistory() As String
            Get
                Return ResourceManager.GetString("SuccessRemoveHistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SWMTRReportGen.log.
        '''</summary>
        Friend ReadOnly Property SWMTRReportGen() As String
            Get
                Return ResourceManager.GetString("SWMTRReportGen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TITLE_GPUPDATE.
        '''</summary>
        Friend ReadOnly Property TitleGPUpdate() As String
            Get
                Return ResourceManager.GetString("TitleGPUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ABOUT.
        '''</summary>
        Friend ReadOnly Property ToolStripMenuItem_About() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem_About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USERGUIDE.
        '''</summary>
        Friend ReadOnly Property ToolStripMenuItem_UserGuide() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem_UserGuide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TOOLTIP.
        '''</summary>
        Friend ReadOnly Property ToolTip_Main_Assistance() As String
            Get
                Return ResourceManager.GetString("ToolTip_Main_Assistance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TOOLTIP.
        '''</summary>
        Friend ReadOnly Property ToolTip_Main_Explorer() As String
            Get
                Return ResourceManager.GetString("ToolTip_Main_Explorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TOOLTIP.
        '''</summary>
        Friend ReadOnly Property ToolTip_Main_GroupBox2() As String
            Get
                Return ResourceManager.GetString("ToolTip_Main_GroupBox2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TOOLTIP.
        '''</summary>
        Friend ReadOnly Property ToolTip_Main_Reboot() As String
            Get
                Return ResourceManager.GetString("ToolTip_Main_Reboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TOOLTIP.
        '''</summary>
        Friend ReadOnly Property ToolTip_Main_remote() As String
            Get
                Return ResourceManager.GetString("ToolTip_Main_remote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TOOLTIP.
        '''</summary>
        Friend ReadOnly Property ToolTip_Main_SiteCode_result() As String
            Get
                Return ResourceManager.GetString("ToolTip_Main_SiteCode_result", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TOOLTIP.
        '''</summary>
        Friend ReadOnly Property ToolTip_UserGuide() As String
            Get
                Return ResourceManager.GetString("ToolTip_UserGuide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TSAgent.log.
        '''</summary>
        Friend ReadOnly Property TSAgent() As String
            Get
                Return ResourceManager.GetString("TSAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ENGLISH.
        '''</summary>
        Friend ReadOnly Property txt_language_text_en() As String
            Get
                Return ResourceManager.GetString("txt_language_text_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FRENCH.
        '''</summary>
        Friend ReadOnly Property txt_language_text_fr() As String
            Get
                Return ResourceManager.GetString("txt_language_text_fr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NO_USER_CONNECTED.
        '''</summary>
        Friend ReadOnly Property txt_logged_no_user() As String
            Get
                Return ResourceManager.GetString("txt_logged_no_user", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DESKTOP.
        '''</summary>
        Friend ReadOnly Property txt_TypePC_text_desktop() As String
            Get
                Return ResourceManager.GetString("txt_TypePC_text_desktop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MOBILE.
        '''</summary>
        Friend ReadOnly Property txt_TypePC_text_mobile() As String
            Get
                Return ResourceManager.GetString("txt_TypePC_text_mobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UpdatesDeployment.log.
        '''</summary>
        Friend ReadOnly Property UpdatesDeployment() As String
            Get
                Return ResourceManager.GetString("UpdatesDeployment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UpdatesHandler.log.
        '''</summary>
        Friend ReadOnly Property UpdatesHandler() As String
            Get
                Return ResourceManager.GetString("UpdatesHandler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UpdatesStore.log.
        '''</summary>
        Friend ReadOnly Property UpdatesStore() As String
            Get
                Return ResourceManager.GetString("UpdatesStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserAffinity.log.
        '''</summary>
        Friend ReadOnly Property UserAffinity() As String
            Get
                Return ResourceManager.GetString("UserAffinity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VirtualApp.log.
        '''</summary>
        Friend ReadOnly Property VirtualApp() As String
            Get
                Return ResourceManager.GetString("VirtualApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wakeprxy-install.log.
        '''</summary>
        Friend ReadOnly Property wakeprxy_install() As String
            Get
                Return ResourceManager.GetString("wakeprxy_install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wakeprxy-uninstall.log.
        '''</summary>
        Friend ReadOnly Property wakeprxy_uninstall() As String
            Get
                Return ResourceManager.GetString("wakeprxy_uninstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WARNING_REINSTALL_CLIENT.
        '''</summary>
        Friend ReadOnly Property WarningReinstallClient() As String
            Get
                Return ResourceManager.GetString("WarningReinstallClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WARNING_SOFTWARE_CACHE.
        '''</summary>
        Friend ReadOnly Property WarningRunSoftwareCache() As String
            Get
                Return ResourceManager.GetString("WarningRunSoftwareCache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WARNING_UNINSTALL_CLIENT.
        '''</summary>
        Friend ReadOnly Property WarningUninstallClient() As String
            Get
                Return ResourceManager.GetString("WarningUninstallClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WARNING_VPN_SLOW_REQUESTS.
        '''</summary>
        Friend ReadOnly Property WarningVPNSlowRequests() As String
            Get
                Return ResourceManager.GetString("WarningVPNSlowRequests", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wedmtrace.log.
        '''</summary>
        Friend ReadOnly Property Wedmtrace() As String
            Get
                Return ResourceManager.GetString("Wedmtrace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WindowsUpdate.log.
        '''</summary>
        Friend ReadOnly Property WindowsUpdate() As String
            Get
                Return ResourceManager.GetString("WindowsUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WUAHandler.log.
        '''</summary>
        Friend ReadOnly Property WUAHandler() As String
            Get
                Return ResourceManager.GetString("WUAHandler", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
